name = "bolt-diy"  # Your Pages project name
main = "build/server/index.js"
compatibility_flags = ["nodejs_compat"]  # Handles crypto/fs/child_process

[build]
command = "pnpm build"
pages_build_output_dir = "build/client"  # Points to Remix client output
