name = "bolt-diy"  # Match your Pages project name
main = "build/server/index.js"
compatibility_flags = ["nodejs_compat"]  # Polyfills crypto/fs/child_process

[build]
command = "pnpm build"
pages_build_output_dir = "build/client"  # Required for Pages; points to Remix assets
